logger:
  transports: ['console']

mongodb:
  uri: 'mongodb://localhost:27017/flask-react-template-dev'

celery:
  broker_url: 'redis://localhost:6379/0'
  result_backend: 'redis://localhost:6379/0'

worker:
  health_check_url: 'http://localhost:8080/api/'

accounts:
  token_signing_key: 'insecure-local-development-signing-key'

sms:
  enabled: false

is_server_running_behind_proxy: false

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

BOOTSTRAP_APP: true
