logger:
  transports: ['console']

mongodb:
  uri: 'mongodb://app-db:27017/flask-react-template-dev'

temporal:
  server_address: 'temporal:7233'

sms:
  enabled: false

is_server_running_behind_proxy: false

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'
