logger:
  transports:
    - 'console'
    - 'datadog'

sms:
  enabled: true

is_server_running_behind_proxy: true

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'
