logger:
  transports:
    - 'console'
    - 'datadog'

sms:
  enabled: true

is_server_running_behind_proxy: true

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

notification:
  token_cleanup_enabled: true
  token_cleanup_days: 30
  token_cleanup_schedule: "0 4 * * *"
