[mypy]
strict = True
show_error_codes = True

[mypy-bson.*]
ignore_missing_imports = True

[mypy-pymongo.*]
ignore_missing_imports = True

[mypy-celery.*]
ignore_missing_imports = True

[mypy-gunicorn.*]
ignore_missing_imports = True

[mypy-sendgrid.*]
ignore_missing_imports = True

[mypy-twilio.*]
ignore_missing_imports = True

[mypy-modules.logger.internal.datadog_handler]
disallow_untyped_calls = False

[mypy-celery_app]
disallow_untyped_decorators = False

[mypy-modules.application.worker]
disallow_untyped_decorators = False
