name: Auto Close PRs Not From Branch

on:
  pull_request:
    types: [opened, reopened]

jobs:
  close-invalid-pr:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.base.ref != 'main'

    permissions:
      pull-requests: write  # Required to comment and close PRs

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Close PR into non-main branches
        run: |
          gh pr close "$PR_URL" --comment "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          COMMENT: |
            ❌ This pull request does not target the correct base branch.

            Please ensure that PRs are opened against the `main` branch of this repo.

            Thank you!
