name: Auto Close Fork PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  close-fork-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Close PR from fork
        run: |
          gh pr close "$PR_URL" --comment "$COMMENT"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          COMMENT: |
            ❌ This pull request was opened from a forked repository.

            Please open a pull request with the **base repo** as `your-username/flask-react-template` and base branch as `your-username/flask-react-template/main`.

            Thank you!
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
