name: Auto Close PRs from Unauthorized Forks

on:
  pull_request:
    types: [opened, reopened]

jobs:
  close-unauthorized-fork:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Check if PR is from fork and author is unauthorized
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prAuthor = pr.user.login;
            const forked = pr.head.repo.full_name !== `${context.repo.owner}/${context.repo.repo}`;

            const allowedUsers = [
              'jjalan',
              'sn1f3rt',
              'KrishnaVAMSI-2003',
              'PunithKosana',
              'bettrhq',
              'amaan-sayyed'
            ];

            if (forked && !allowedUsers.includes(prAuthor)) {
              const message = `❌ Hi @${prAuthor}, your pull request was opened from a fork and you are not authorized to contribute to this repository.

            Only internal team members are allowed to raise PRs to this repo. Please fork the repo and keep your changes in your own fork.

            This PR has been **automatically closed**.`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: message
              });

              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
            } else {
              console.log("PR is either not from a fork or author is authorized.");
            }
