name: clean_on_pr_closed

on:
  pull_request_target:
    types: [ closed ]

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@v2.5
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      app_name: frm-boilerplate
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
 
  clean_temporal:
    needs: clean  # Ensure Temporal cleanup happens after app cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with DigitalOcean Kubernetes
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          echo "$DO_ACCESS_TOKEN" | doctl auth init
          doctl kubernetes cluster kubeconfig save ${{ vars.DO_CLUSTER_ID }}

      - name: Delete PR-Specific Temporal Deployment
        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
        run: |
          kubectl delete deployment temporal-${{ github.event.pull_request.number }} -n $KUBE_NS || true
          kubectl delete service temporal-${{ github.event.pull_request.number }}-service -n $KUBE_NS || true